CREATE DATABASE RaceDay;
Go
USE RaceDay;
Go
-- Table Creation
CREATE TABLE Participant 
(
ParticipantID INT IDENTITY(1,1) PRIMARY KEY,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
CellNumber VARCHAR(15) NOT NULL,
Address VARCHAR(200) NOT NULL
);
CREATE TABLE Organiser
(
OrganiserID INT IDENTITY(1,1) PRIMARY KEY,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Address VARCHAR(200) NOT NULL
);
CREATE TABLE Account
(
AccountID INT IDENTITY(1,1) PRIMARY KEY,
OrganiserID INT FOREIGN KEY REFERENCES Organiser(OrganiserID) NULL,
ParticipantID INT FOREIGN KEY REFERENCES Participant(ParticipantID) NULL,
AuthenticationRole VARCHAR(30) NOT NULL,
Email VARCHAR(100) UNIQUE,
PasswordHash VARCHAR(230) NOT NULL
);

CREATE TABLE Event 
(
EventID INT IDENTITY(100,1) PRIMARY KEY,
OrganiserID int FOREIGN KEY REFERENCES Organiser(OrganiserID),
EventName VARCHAR(50) NOT NULL,
Description VARCHAR(100) NOT NULL,
EventType VARCHAR(50) NOT NULL,
EventDate DATETIME2 NOT NULL,
EventDuration VARCHAR(50) NOT NULL,
Location VARCHAR(100) NOT NULL,
Distance VARCHAR(50) NOT NULL
);
CREATE TABLE Category
(
CategoryID INT IDENTITY(1010,1) PRIMARY KEY,
EventID INT FOREIGN KEY REFERENCES Event(EventID),
CategoryName VARCHAR(30) NOT NULL,
MinAge INT NOT NULL,
MaxAge INT NOT NULL
);
CREATE TABLE Enrolment
(
EnrolmentID INT IDENTITY(1,1) PRIMARY KEY,
AccountID INT FOREIGN KEY REFERENCES Account(AccountID),
CategoryID INT FOREIGN KEY REFERENCES Category(CategoryID),
EventID INT FOREIGN KEY REFERENCES Event(EventID),
EnrolmentDate DATETIME2 NOT NULL
);
CREATE TABLE RaceResults
(
RaceResultsID INT IDENTITY(1101,1) PRIMARY KEY,
EnrolmentID INT UNIQUE FOREIGN KEY REFERENCES Enrolment(EnrolmentID),
FinishTime VARCHAR(30) NOT NULL,
FinishPosition INT NOT NULL,
PerformanceDetails VARCHAR(255) NULL
);
CREATE TABLE Awards
(
AwardsID INT IDENTITY(1,1) PRIMARY KEY,
RaceResultsID INT FOREIGN KEY REFERENCES RaceResults(RaceResultsID),
AwardDetails VARCHAR(255) NULL
);
