name: Part 1 Documentation Check
on:
 push:
 pull_request:
jobs:
 validate-part1:
   runs-on: ubuntu-latest
   steps:- name: Checkout repository
  uses: actions/checkout@v4- name: Check docs folder
  run: test -d docs- name: Check ERD
  run: test -f docs/PROG6212_ ST10478144_ POE_ RaceDay ERD Diagram- name: Check API Endpoint Plan
  run: test -f docs/RaceDay_API Endpoint Planning.pdf- name: Check SQL Script
  run: test -f docs/RaceDay Database SQLQuery.sql- name: Check README
  run: test -f README.md
